### ISSUE TITLE
No response after clicking submit button

### ISSUE THREAD

**Issue by choufree** [JBEI/ice#25] opened 2015-06-07 18:39 UTC
Dear there,

I have been having the problem since last week. I just want to submit one RBS into part registry. I finished filled in all the required information and clicked 'submit' botton. However, there is no response afterwards. I repeated the process for many times the same problem came out. I am wondering what i can do to submit several RBS as parts

Thanks,

**Comment by hplahar** [comment] 2015-06-09 21:41
Is this on the JBEI registry? If not which version of the registry were you using?

**Comment by hplahar** [comment] 2015-06-23 17:13
Please re-open and provide more information when you can. Closing this now since I cannot reproduce. To upload multiple parts, you can use the bulk upload feature

**Closed by hplahar** 2015-06-23 17:13 UTC
Labels: invalid
